GET http://localhost:3000/users

###
# create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Admin",
  "password": "password"
}

###
# login succeeds
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "Admin",
  "password": "password"
}

###
# login fails
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "User",
  "password": "password"
}

###
# login failed by password
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "Admin",
  "password": "user"
}